line-length = 120

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]


[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = ["cartographer"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
