name: Auto Label PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Label PR based on title and files
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/auto-label-pr.js');
            await script({github, context, console});
