name: Continuous integration

on:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check lockfile
        run: |
          pdm lock -dG :all --check
      - name: Install dependencies
        run: |
          pdm install -dG :all
      - name: Linting
        uses: astral-sh/ruff-action@v1
      - name: Type check
        run: |
          pip install basedpyright && basedpyright
      - name: Build
        run: |
          pdm build
